[network_controller]
x.x.x.x ansible_user=hoss

[media_server]
x.x.x.x ansible_user=hoss

[nas]
x.x.x.x ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[network_gear]
# EdgeRouter uses vault_er_pass
edgerouter ansible_host=x.x.x.x ansible_user="{{ vault_er_user }}" ansible_password="{{ vault_er_pass }}"

# Access Point uses vault_ap_pass on Port 22
# Host IP is device IP, not the controller IP
access_point ansible_host=x.x.x.x ansible_port=22 ansible_user="{{ vault_ap_user }}" ansible_password="{{ vault_ap_pass }}" ansible_ssh_extra_args='-o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedAlgorithms=+ssh-rsa -o KexAlgorithms=+diffie-hellman-group1-sha1'

[network_gear:vars]
ansible_connection=ssh
ansible_ssh_transfer_method=scp
ansible_python_interpreter=/usr/bin/python3
ansible_gather_facts=false
# Use raw/password auth only, ignore key checks
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PreferredAuthentications=password -o PubkeyAuthentication=no'

[ubuntu_servers:children]
network_controller
media_server